ExcelExport/Models/Employees.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace ExcelExport.Models
{
    public class Employees
    {
        [Key]
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string TitleOfCourtesy { get; set; }
        public string HomePhone { get; set; }
        public DateTime BirthDate { get; set; }

    }
}

ExcelExport/Models/ErrorViewModel.cs
using System;

namespace ExcelExport.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExcelExport/Models/ExportContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Composition;
using System.Linq;
using System.Threading.Tasks;

namespace ExcelExport.Models
{
    public class ExportContext : DbContext
    {
        public ExportContext(DbContextOptions<ExportContext> contextOptions) : base(contextOptions)
        {
        }
        public DbSet<Employees> Employees { get; set; }
    }
}

ExcelExport/Controllers/ExportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using ClosedXML.Excel;
using ExcelExport.Abstact;
using ExcelExport.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace ExcelExport.Controllers
{
    public class ExportController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IMemoryCache _memoryCache;
        public ExportController(IEmployeeService employeeService, IMemoryCache memoryCache)
        {
            _employeeService = employeeService;
            _memoryCache = memoryCache;
        }

        [HttpGet]
        public ActionResult Index() => View();

        const string key = "allEmployeeData";
        [HttpPost]
        public async Task<ActionResult> ExportToCvs()
        {
            if (_memoryCache.Get(key) == null)
            {
                var employees = await _employeeService.GetEmployeeList();
                _memoryCache.Set(key, employees);
            }
            var employeeData = _memoryCache.Get<List<Employees>>(key);
            var builder = new StringBuilder();
            builder.AppendLine("EmployeeID,FirstName,LastName,Title,Address,City,PostalCode,TitleOfCourtesy,HomePhone,BirthDate");
            foreach (var employee in employeeData)
            {
                builder.AppendLine($"{employee.EmployeeID},{employee.FirstName},{employee.LastName}," +
                                   $"{employee.Title},{employee.Address}," +
                                   $"{employee.City},{employee.PostalCode},{employee.TitleOfCourtesy},{employee.HomePhone},{employee.BirthDate.ToLongDateString()}");
            }
            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", "EmployeeList");
        }

        [HttpPost]
        public async Task<ActionResult> ExportToExcel()
        {
            if (_memoryCache.Get(key) == null)
            {
                var employees = await _employeeService.GetEmployeeList();
                _memoryCache.Set(key, employees);
            }
            var employeeData = _memoryCache.Get<List<Employees>>(key);
            using (var workbook=new XLWorkbook())
            {
                var workSheet = workbook.Worksheets.Add("Employees");
                var currentRow = 1;
                workSheet.Cell(currentRow, 1).Value = "EmployeeID";
                workSheet.Cell(currentRow, 2).Value = "First Name";
                workSheet.Cell(currentRow, 3).Value = "Last Name";
                workSheet.Cell(currentRow, 4).Value = "Title";
                workSheet.Cell(currentRow, 5).Value = "City";
                workSheet.Cell(currentRow, 6).Value = "Postal Code";
                workSheet.Cell(currentRow, 7).Value = "Title Of Courtesy";
                workSheet.Cell(currentRow, 8).Value = "Home Phone";
                workSheet.Cell(currentRow, 9).Value = "Birth Date";
                foreach (var employee in employeeData)
                {
                    currentRow++;
                    workSheet.Cell(currentRow, 1).Value = employee.EmployeeID;
                    workSheet.Cell(currentRow, 2).Value =employee.FirstName ;
                    workSheet.Cell(currentRow, 3).Value = employee.LastName;
                    workSheet.Cell(currentRow, 4).Value = employee.Title;
                    workSheet.Cell(currentRow, 5).Value = employee.City;
                    workSheet.Cell(currentRow, 6).Value = employee.PostalCode;
                    workSheet.Cell(currentRow, 7).Value = employee.TitleOfCourtesy;
                    workSheet.Cell(currentRow, 8).Value = employee.HomePhone;
                    workSheet.Cell(currentRow, 9).Value = employee.BirthDate;
                }
              
                using (var stream=new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "EmployeeList.xlsx");
                }
            }
        }

    }
}

ExcelExport/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ExcelExport.Models;

namespace ExcelExport.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExcelExport/Views/Export/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Export To Excel</h1>

<form asp-action="ExportToCvs" asp-controller="Export">
    <button type="submit" class="btn btn-outline-success"> Export To Cvs</button>
</form>
<form asp-action="ExportToExcel" asp-controller="Export">
    <button type="submit" class="btn btn-outline-success"> Export To Excel</button>
</form>

ExcelExport/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExcelExport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExcelExport</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExcelExport</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Export" asp-action="Index">Export To Cvs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Export" asp-action="Index">Export To Excel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ExcelExport - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>